name: Test Workflow
on:
  push:
    branches:
      - dev
      - main

jobs:
  set-env-vars:
    runs-on: windows-latest
    outputs:
      event_name: ${{ steps.set-env-vars.outputs.event_name }}
    steps:
      - name: Debug Event Name
        run: |
          echo "GITHUB EVENT NAME: ${{ github.event_name }}"

      - name: Set env vars
        id: set-env-vars
        shell: bash  # Ensure using bash instead of default PowerShell
        run: |
          echo "event_name=${{ github.event_name }}" | tee -a $GITHUB_ENV $GITHUB_OUTPUT

  print-env-vars:
    runs-on: windows-latest
    needs: set-env-vars
    steps:
      - name: Print event_name
        run: |
          echo "event_name from needs: ${{ needs.set-env-vars.outputs.event_name }}"
