name: Test Workflow
on:
  push:
    branches:
      - dev
      - main

jobs:
  set-env-vars:
    runs-on: windows-latest
    outputs:
      event_name: ${{ steps.set-env-vars.outputs.event_name }}
    steps:
      - name: Debug Event Name
        run: |
          echo "GITHUB EVENT NAME: ${{ github.event_name }}"

      - name: Set env vars
        id: set-env-vars
        run: |
          echo "event_name=${{ github.event_name }}" >> $GITHUB_OUTPUT

  print-env-vars:
    runs-on: windows-latest
    needs: set-env-vars
    steps:
      - name: Print event_name
        run: |
          echo "event_name from needs: ${{ needs.set-env-vars.outputs.event_name }}"

  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"