name: Test Workflow
on:
  push:
    branches:
      - dev
      - main

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    outputs:
      event_name: ${{ steps.set-env-vars.outputs.event_name }}
      ref_name: ${{ steps.set-env-vars.outputs.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github Environment Variables
        id: set-env-vars
        uses: ./.github/actions/set-env-vars

  print-env-vars:
    runs-on: windows-latest
    needs: set-env-vars
    steps:
      - name: Print event_name
        run: |
          echo "event_name from needs: ${{ needs.set-env-vars.outputs.event_name }}"
          echo "ref_name from needs: ${{ needs.set-env-vars.outputs.ref_name }}"
      - name: Check ref name
        if: "${{ needs.set-env-vars.outputs.ref_name }}" == 'refs/heads/dev'
        run: echo "This is the dev branch"

  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: windows-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"