name: Create prod promotion pull request
on:
  push:
    branches:
      - dev
jobs:
  prodPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: prod
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: prod-promotion