name: Create release-1 PR
on:
  push:
    branches:
      - prod
jobs:
  release1Promotion:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release-1
          title: "Release 1: Creator-spring"
          body: |
            PR description:
            - [Some link][1]
            
            [1]: https://www.google.com