name: Create release-1 PR
on:
  push:
    branches:
      - prod
jobs:
  release1Promotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release-1
      - name: Reset promotion branch
        run: |
          git fetch origin prod:prod
          git reset --hard prod
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release1-promotion
          title: "Release 1: Creator-spring"